export default {
    AC: ['Ace', 'Aceca', 'Cobra', '378 GT Zagato'],
    Acura: [
        'CL',
        'EL',
        'Integra',
        'MDX',
        'NSX',
        'RL',
        'RSX',
        'SLX',
        'TL',
        'TSX',
        'RDX',
        'CSX',
        'ZDX',
        'Legend',
        'ILX',
        'RLX',
        'TLX',
    ],
    'Alfa Romeo': [
        '145',
        '146',
        '147',
        '155',
        '156',
        '164',
        '166',
        '33',
        '6',
        '75',
        '90',
        'Alfasud',
        'Sprint',
        'Alfetta',
        'Arna',
        'Giulia',
        'Giulietta',
        'GT',
        'GTA Coupe',
        'GTV',
        'Montreal',
        'RZ',
        'Spider',
        'SZ',
        'Brera',
        '159',
        '8C Competizione',
        'MiTo',
        '4C',
        'Disco Volante',
        '2600',
        '105/115',
        '1900',
        '6C',
        'Stelvio',
    ],
    Alpine: ['A110', 'A310', 'A610', 'GTA'],
    Aro: ['10', '24'],
    Asia: ['Rocsta', 'Retona', 'Topic'],
    'Aston Martin': [
        'Bulldog',
        'DB7',
        'DB9',
        'Lagonda',
        'Tickford Capri',
        'V12 Vanquish',
        'V8 Vantage',
        'Virage',
        'V8 Zagato',
        'DBS',
        'Rapide',
        'V12 Vantage',
        'Cygnet',
        'V12 Zagato',
        'One-77',
        'DB5',
        'DB11',
    ],
    Audi: [
        '200',
        '50',
        'A2',
        'A3',
        'A4',
        'A4 allroad',
        'A6',
        'A8',
        'A6 allroad',
        'Cabriolet',
        'Coupe',
        'NSU RO 80',
        'quattro',
        'RS4',
        'RS6',
        'S2',
        'S3',
        'S4',
        'S6',
        'S8',
        'TT',
        'Q7',
        '90',
        'V8',
        '100',
        '80',
        'R8',
        'A5',
        'RS2',
        'Q5',
        'RS5',
        'A1',
        'A7',
        'RS3',
        'Q3',
        'S5',
        'S7',
        'RS7',
        'RS Q3',
        'SQ5',
        'S1',
        'TTS',
        'TT RS',
        '920',
        'Typ R',
        'Q2',
        'SQ7',
    ],
    Austin: [
        'Allegro',
        'Ambassador',
        'Maestro',
        'Maxi',
        'Metro',
        'Mini',
        'Montego',
        'Princess',
    ],
    Autobianchi: ['A 112'],
    Bentley: [
        'Arnage',
        'Azure',
        'Brooklands',
        'Continental',
        'Continental Flying Spur',
        'Mulsanne',
        'Turbo R',
        'Flying Spur',
        'Continental GT',
        'Eight',
        'S',
        'Bentayga',
        'R Type',
        'T-Series',
        'Mark VI',
    ],
    Bertone: ['Freeclimber'],
    Bitter: ['Type 3'],
    BMW: [
        '3er',
        '5er',
        '6er',
        '7er',
        '8er',
        '1er',
        '02 (E10)',
        'X5',
        'X1',
        'X3',
        'X6',
        'Z1',
        'Z3',
        'Z4',
        'Z8',
        '4er',
        'i3',
        '2er',
        'i8',
        '2er Active Tourer',
        'X4',
        '1M',
        'M3',
        'M4',
        'M5',
        'M6',
        'Z3 M',
        'X5 M',
        'X6 M',
        'Z4 M',
        '2er Grand Tourer',
        '2000 C/CS',
        '315',
        '321',
        '326',
        '340',
        'M2',
        'New Class',
        '3/15',
        '3200',
        '327',
        '501',
        '502',
        '503',
        '507',
        '600',
        '700',
        'E9',
        'E3',
        'X2 Concept',
    ],
    Bristol: ['Blenheim', 'Fighter', 'Blenheim Speedster'],
    Bugatti: ['EB 110', 'EB 112', 'EB Veyron 16.4', 'Chiron', 'Type 55'],
    Buick: [
        'Century',
        'GL8',
        'LeSabre',
        'Park Avenue',
        'Reatta',
        'Regal',
        'Rendezvous',
        'Riviera',
        'Roadmaster',
        'Skylark',
        'Rainer',
        'LaCrosse',
        'Terraza',
        'Lucerne',
        'Enclave',
        'Excelle',
        'Electra',
        'Encore',
        'Special',
        'Verano',
        'Estate Wagon',
        'Skyhawk',
        'Super',
        'Limited',
        'Envision',
    ],
    Cadillac: [
        'Allante',
        'Catera',
        'CTS',
        'De Ville',
        'Eldorado',
        'Escalade',
        'LSE',
        'Seville',
        'XLR',
        'SRX',
        'Brougham',
        'BLS',
        'STS',
        'DTS',
        'Fleetwood',
        'ATS',
        'XTS',
        'Sixty Special',
        'ELR',
        'CTS-V',
        'ATS-V',
        'CT6',
        'Series 62',
        'XT5',
    ],
    Callaway: ['C12'],
    Carbodies: ['FX4'],
    Caterham: ['21', 'Seven', 'CSR'],
    Chevrolet: [
        'Alero',
        'Astra',
        'Astro',
        'Beretta',
        'Blazer',
        'Camaro',
        'Caprice',
        'Cavalier',
        'Celta',
        'Corsa',
        'Corsica',
        'Corvette',
        'Impala',
        'Lumina',
        'Lumina APV',
        'Malibu',
        'Monte Carlo',
        'Monza',
        'Niva',
        'Omega',
        'Prizm',
        'S-10 Pickup',
        'SSR',
        'Suburban',
        'Tahoe',
        'Tracker',
        'TrailBlazer',
        'Trans Sport',
        'Vectra',
        'Venture',
        'Zafira',
        'Aveo',
        'Cobalt',
        'Classic',
        'Uplander',
        'Equinox',
        'Captiva',
        'Evanda',
        'Lacetti',
        'Lanos',
        'Spark',
        'Metro',
        'Nubira',
        'Rezzo',
        'Viva',
        'Epica',
        'HHR',
        'Silverado',
        'Avalanche',
        'C-10',
        'Starcraft',
        'Van',
        'Colorado',
        'Tavera',
        'Sail',
        'LUV D-MAX',
        'Cruze',
        'Cruze (HR)',
        'Celebrity',
        'Traverse',
        'Chevette',
        'Orlando',
        'Volt',
        'Sonic',
        'Blazer K5',
        'Citation',
        'Express',
        'MW',
        'Kalos',
        'SS',
        'Bel Air',
        'Master',
        'Special DeLuxe',
        'El Camino',
        'Bolt',
        'Chevelle',
        'Fleetmaster',
        'C/K',
        'Deluxe',
        'Corvair',
    ],
    Chrysler: [
        'Concorde',
        'Crossfire',
        'Le Baron',
        'LHS',
        'Neon',
        'New Yorker',
        'Pacifica',
        'Prowler',
        'PT Cruiser',
        'Sebring',
        'Stratus',
        'Town & Country',
        'Viper',
        'Vision',
        'Voyager',
        '300C',
        '300M',
        'Intrepid',
        'Saratoga',
        'Aspen',
        'Nassau',
        'Fifth Avenue',
        'Dynasty',
        'Imperial',
        'Cirrus',
        '200',
        'TC by Maserati',
        '300C SRT8',
        'Imperial Crown',
        '180',
        '300',
        'Cordoba',
        'Windsor',
        'Newport',
        '300 Letter Series',
    ],
    Citroen: [
        '2 CV',
        'AMI',
        'AX',
        'Berlingo',
        'BX',
        'C3',
        'C3 Picasso',
        'C5',
        'C8',
        'CX',
        'Dyane',
        'Evasion',
        'GS',
        'LN',
        'Saxo',
        'Visa',
        'Xantia',
        'XM',
        'Xsara',
        'Xsara Picasso',
        'ZX',
        'C4',
        'C4 Picasso',
        'C6',
        'C1',
        'C2',
        'Jumpy',
        'C-Crosser',
        'DS3',
        'DS4',
        'C4 Aircross',
        'C-Elysee',
        'DS5',
        'C4 Cactus',
        'C-ZERO',
        'Traction Avant',
        'DS',
        'SM',
        'E-Mehari',
        'Spacetourer',
        'Nemo',
    ],
    Cizeta: ['V16t'],
    Coggiola: ['T Rex'],
    Dacia: [
        '1310',
        '1410',
        'Nova',
        'Solenza',
        '1300',
        'Logan',
        'Sandero',
        'Duster',
        'Lodgy',
        'Dokker',
    ],
    Daewoo: [
        'Nubira',
        'Arcadia',
        'Chairman',
        'Espero',
        'Evanda',
        'Kalos',
        'Korando',
        'Lacetti',
        'Lanos',
        'LeMans',
        'Leganza',
        'Magnus',
        'Matiz',
        'Musso',
        'Nexia',
        'Prince',
        'Racer',
        'Rezzo',
        'Tico',
        'Damas',
        'Tacuma',
        'G2X',
        'Tosca',
        'Winstorm',
        'Gentra',
        'Sens',
    ],
    DAF: ['66', '46'],
    Daihatsu: [
        'Altis',
        'Applause',
        'Atrai',
        'Charade',
        'Charmant',
        'Cuore',
        'Feroza',
        'Leeza',
        'MAX',
        'Mira',
        'Move',
        'Naked',
        'Sirion',
        'Terios',
        'Wildcat',
        'YRV',
        'Opti',
        'Rocky',
        'Storia',
        'Pyzar',
        'Delta Wagon',
        'Trevis',
        'Copen',
        'Esse',
        'Be-go',
        'Boon',
        'Materia',
        'Tanto',
        'Ceria',
        'Sonica',
        'Xenia',
        'Mira Gino',
        'Taft',
        'Coo',
        'Gran Move',
        'Midget',
        'Rugger',
        'Move Latte',
    ],
    Daimler: ['DS420', 'XJ40', 'XJS', 'X300', 'Sovereign (XJ6)', 'X308', 'X350'],
    DeLorean: ['DMC-12'],
    'De Tomaso': ['Bigua', 'Guara', 'Mangusta', 'Pantera', 'Vallelunga'],
    Dodge: [
        'Avenger',
        'Caravan',
        'Dakota',
        'Durango',
        'Intrepid',
        'Monaco',
        'Shadow',
        'Spirit',
        'Stealth',
        'RAM',
        'Ramcharger',
        'Caliber',
        'Magnum',
        'Neon',
        'Stratus',
        'Viper',
        'Charger',
        'Nitro',
        'Daytona',
        'Challenger',
        'Journey',
        'Aries',
        'Dynasty',
        '600',
        'Omni',
        'Dart',
        'Lancer',
        'WC',
        'Mayfair',
        'Charger Daytona',
        'Diplomat',
    ],
    Doninvest: ['Assol', 'Kondor', 'Orion'],
    Eagle: ['Premier', 'Summit', 'Talon', 'Vision'],
    FAW: [
        'City Golf',
        'Jinn',
        'Besturn B50',
        'Vita',
        'V2',
        'V5',
        'Besturn B70',
        'Oley',
        'Besturn X80',
    ],
    Ferrari: [
        '208/308',
        '400',
        '412',
        '456',
        '550',
        'Enzo',
        'F50',
        'F40',
        '575M',
        'Mondial',
        'Testarossa',
        '328',
        '348',
        '360',
        '512 M',
        'F355',
        '612',
        '599',
        'F430',
        'California',
        '458',
        'FF',
        'F12berlinetta',
        '512 BB',
        'LaFerrari',
        '512 TR',
        '488',
        'FXX K',
        'GTC4Lusso',
        '250 GTO',
        '812 Superfast',
    ],
    Fiat: [
        '124',
        '126',
        '127',
        '128',
        '130',
        '131',
        '132',
        '500',
        'Argenta',
        'Brava',
        'Bravo',
        'Cinquecento',
        'Croma',
        'Duna',
        'Fiorino',
        'Marea',
        'Multipla',
        'Palio',
        'Panda',
        'Punto',
        'Regata',
        'Ritmo',
        'Seicento',
        'Siena',
        'Stilo',
        'Strada',
        'Tempra',
        'Tipo',
        'Ulysse',
        'Uno',
        'X 1/9',
        '238',
        'Idea',
        'Sedici',
        '900T',
        'Albea',
        'Barchetta',
        'Coupe',
        'Scudo',
        'Linea',
        '600',
        'Doblo',
        'Qubo',
        '500L',
        'Freemont',
        '500X',
        '124 Sport Spider',
        '508',
        '124 Spider',
        'Fullback',
    ],
    Ford: [
        'Capri',
        'Consul',
        'Cougar',
        'Escort',
        'Excursion',
        'Expedition',
        'Explorer',
        'Fiesta',
        'Focus',
        'Galaxy',
        'Granada',
        'KA',
        'Maverick',
        'Mondeo',
        'Probe',
        'Puma',
        'Scorpio',
        'Sierra',
        'Taunus',
        'Tempo',
        'Aerostar',
        'Aspire',
        'Contour',
        'Crown Victoria',
        'LTD Crown Victoria',
        'Econoline',
        'Escape',
        'Mustang',
        'Taurus',
        'Thunderbird',
        'Windstar',
        'Five Hundred',
        'Freestyle',
        'Orion',
        'GT',
        'Ranger',
        'S-MAX',
        'Tourneo Connect',
        'F-150',
        'Bronco',
        'Edge',
        'C-MAX',
        'Freestar',
        'Taurus X',
        'Granada (North America)',
        'Kuga',
        'Festiva',
        'Flex',
        'Explorer Sport Trac',
        'Ixion',
        'Everest',
        'Fairmont',
        'Escort (North America)',
        'Fusion (North America)',
        'Fusion',
        'Laser',
        'B-MAX',
        'Ranger (North America)',
        'EcoSport',
        'Bronco-II',
        'Tourneo Custom',
        'Tourneo Courier',
        'Focus (North America)',
        'Fiesta ST',
        'Focus ST',
        'Focus RS',
        'Mondeo ST',
        'Telstar',
        'Spectron',
        'Model A',
        'Model T',
        'Galaxie',
        'Torino',
        'Custom',
        'Fairlane',
        'Ranchero',
        'GT40',
        'Zephyr',
        'GPA',
        'M151',
    ],
    FSO: ['125p', '126p', '127p', '132p', 'Polonez'],
    GAZ: [
        '22 «Volga»',
        '2308 «Ataman»',
        '14 «Chayka»',
        'M-20 «Pobeda»',
        '21 «Volga»',
        '24 «Volga»',
        '69',
        '13 «Chayka»',
        'Volga Siber',
        'M1',
        '2330 «Tigr»',
        '3102 «Volga»',
        '31029 «Volga»',
        '3105 «Volga»',
        '3110 «Volga»',
        '31105 «Volga»',
        '3111 «Volga»',
        '3103 «Volga»',
        '12 ZIM',
        '67',
        'M-72',
    ],
    GMC: [
        'Envoy',
        'Jimmy',
        'Savana',
        'Sonoma',
        'Yukon',
        'Safari',
        'Sierra',
        'Suburban',
        'Acadia',
        'Typhoon',
        'Syclone',
        'Terrain',
        'Canyon',
        'Vandura',
    ],
    Hindustan: ['Contessa', 'Ambassador'],
    Holden: [
        'Apollo',
        'Barina',
        'Calais',
        'Commodore',
        'Frontera',
        'Jackaroo',
        'Monaro',
        'Rodeo',
        'Statesman',
        'UTE',
        'Astra',
        'Caprice',
        'Vectra',
        'Zafira',
        'Cruze',
    ],
    Honda: [
        'Accord',
        'Avancier',
        'Capa',
        'City',
        'Civic',
        'Concerto',
        'CR-V',
        'CR-X',
        'Domani',
        'Fit',
        'HR-V',
        'Insight',
        'Inspire',
        'Jazz',
        'Legend',
        'Life',
        'Logo',
        'Mobilio',
        'Odyssey (North America)',
        'Orthia',
        'Passport',
        'Pilot',
        'Prelude',
        'Quint',
        'S2000',
        'Saber',
        'S-MX',
        'Stepwgn',
        'Stream',
        "That''S",
        'Today',
        'Torneo',
        'Vamos',
        'Vigor',
        'Z',
        'Partner',
        'Element',
        'Fit Aria',
        'FR-V',
        'Integra',
        'Integra SJ',
        'NSX',
        'Ridgeline',
        'Rafaga',
        'Airwave',
        'Shuttle',
        'Edix',
        'Crossroad',
        'Elysion',
        'MDX',
        'Beat',
        'Ascot',
        'FCX Clarity',
        'CR-Z',
        'Crosstour',
        'Freed',
        'Zest',
        'Civic Ferio',
        'Odyssey',
        'Vezel',
        'Civic Type R',
        'Acty',
        'Ascot Innova',
        'S660',
        'Fit Shuttle',
    ],
    Hummer: ['H1', 'H2', 'H3'],
    Hyundai: [
        'Accent',
        'Atos',
        'Centennial',
        'Dynasty',
        'Galloper',
        'Getz',
        'Elantra',
        'Matrix',
        'Excel',
        'Scoupe',
        'Santa Fe',
        'Santamo',
        'Sonata',
        'Stellar',
        'Terracan',
        'Trajet',
        'XG',
        'Tucson',
        'Coupe',
        'Lavita',
        'Verna',
        'Grandeur',
        'Starex (H-1)',
        'Veracruz',
        'Tiburon',
        'Tuscani',
        'i30',
        'Avante',
        'Genesis',
        'i20',
        'i10',
        'ix55',
        'Lantra',
        'Equus',
        'ix35',
        'Marcia',
        'Pony',
        'Veloster',
        'Solaris',
        'Genesis Coupe',
        'ix20',
        'i40',
        'Maxcruz',
        'Grace',
        'Aslan',
        'Entourage',
        'Creta',
        'IONIQ',
    ],
    Izh: ['2126 «Oda»', '21261 «Fabula»', 'Moskvich-412', '2125 «Kombi»', '2717'],
    Infiniti: [
        'FX',
        'Q',
        'EX',
        'M',
        'G',
        'I',
        'J',
        'QX56',
        'JX',
        'QX70',
        'Q50',
        'QX50',
        'Q60',
        'QX60',
        'QX80',
        'Q70',
        'Q40',
        'QX4',
        'Q30',
        'QX30',
    ],
    Innocenti: ['Elba', 'Mille', 'Mini'],
    Isdera: ['Commendatore 112i', 'Imperator 108i', 'Spyder'],
    Isuzu: [
        'Ascender',
        'Aska',
        'Axiom',
        'KB',
        'Gemini',
        'Impulse',
        'Piazza',
        'Trooper',
        'VehiCross',
        'Rodeo',
        'Wizard',
        'Bighorn',
        'Stylus',
        'D-Max',
        'Amigo',
        'TF (Pickup)',
        'MU-7',
        'MU',
        'MU-X',
        'Hombre',
    ],
    Jaguar: [
        'E-type',
        'S-Type',
        'X-Type',
        'XJ',
        'XJS',
        'XK',
        'XF',
        'XJ220',
        'F-Type',
        'XE',
        'XFR',
        'XKR',
        'XJR',
        'F-Pace',
        'F-Type SVR',
        'Mark 2',
    ],
    Jeep: [
        'Cherokee',
        'CJ',
        'Grand Cherokee',
        'Wrangler',
        'Commander',
        'Compass',
        'Liberty (North America)',
        'Liberty (Patriot)',
        'Grand Wagoneer',
        'Renegade',
        'Grand Cherokee SRT8',
    ],
    Kia: [
        'Capital',
        'Carens',
        'Carnival',
        'Clarus',
        'Concord',
        'Enterprise',
        'Joice',
        'Magentis',
        'Opirus',
        'Potentia',
        'Pride',
        'Retona',
        'Rio',
        'Sephia',
        'Shuma',
        'Sorento',
        'Sportage',
        'Visto',
        'Avella',
        'Sedona',
        'Cerato',
        'Spectra',
        'Optima',
        "Cee''d",
        'Mohave (Borrego)',
        'Picanto',
        'Soul',
        'Elan',
        'Venga',
        'Cadenza',
        'X-Trek',
        'Ray',
        'Quoris',
        "Cee''d GT",
        'Niro',
        'Stinger',
    ],
    Lamborghini: [
        'Countach',
        'Diablo',
        'Espada',
        'Jalpa',
        'Jarama',
        'LM001',
        'LM002',
        'Murcielago',
        'Urraco',
        'Gallardo',
        'Reventon',
        'Aventador',
        'HuracÃ¡n',
        'Veneno',
        'Sesto Elemento',
        'Centanario',
        '350/400 GT',
        'Islero',
        'Miura',
        'Silhouette',
        'Urus Concept',
        'Egoista',
    ],
    Lancia: [
        'Beta',
        'Dedra',
        'Delta',
        'Fulvia',
        'Gamma',
        'Kappa',
        'Lybra',
        'Phedra',
        'Prisma',
        'Thema',
        'Thesis',
        'Zeta',
        'Hyena',
        'A 112',
        'Monte Carlo',
        'Ypsilon',
        'Musa',
        'Trevi',
        'Y10',
        'Voyager',
        'Flavia',
        'Appia',
        'Aurelia',
        'Flaminia',
        'Lambda',
        'Rally 037',
        'Stratos',
    ],
    'Land Rover': [
        'Discovery',
        'Freelander',
        'Range Rover',
        'Range Rover Sport',
        'Series I',
        'Range Rover Evoque',
        'Defender',
        'Series II',
        'Series III',
        'Discovery Sport',
        'Range Rover Velar',
    ],
    Lexus: [
        'ES',
        'GX',
        'IS',
        'LS',
        'LX',
        'RX',
        'SC',
        'GS',
        'HS',
        'CT',
        'LFA',
        'RC',
        'NX',
        'IS F',
        'RC F',
        'GS F',
        'LC',
    ],
    Lincoln: [
        'Aviator',
        'Navigator',
        'Town Car',
        'Continental',
        'LS',
        'Mark VIII',
        'Mark LT',
        'MKX',
        'MKZ',
        'MKT',
        'MKS',
        'Mark VII',
        'MKC',
        'Capri',
        'Premiere',
        'Mark IV',
    ],
    Lotus: [
        'Eclat',
        'Elan',
        'Elise',
        'Elite',
        'Esprit',
        'Europa S',
        'Excel',
        'Exige',
        'Europa',
        'Evora',
        '340R',
    ],
    LTI: ['TX'],
    Mahindra: [
        'Armada',
        'Bolero',
        'CJ-3',
        'Commander',
        'NC 640 DP',
        'CL',
        'Scorpio',
        'Voyager',
        'Marshal',
        'Xylo',
        'MM',
        'Verito',
    ],
    Marcos: ['LM 400', 'LM 500', 'Mantis', 'Marcasite', 'GTS'],
    Maruti: [
        '1000',
        '800',
        'Alto',
        'Baleno',
        'Esteem',
        'Gypsy',
        'Omni',
        'Versa',
        'Wagon R',
        'Zen',
    ],
    Maserati: [
        '228',
        '3200 GT',
        '420',
        '4200 GT',
        'Barchetta Stradale',
        'Biturbo',
        'Chubasco',
        'Ghibli',
        'Indy',
        'Karif',
        'Khamsin',
        'Kyalami',
        'Merak',
        'Mexico',
        'Quattroporte',
        'Royale',
        'Shamal',
        'Bora',
        'GranTurismo',
        'MC12',
        'Levante',
    ],
    Mazda: [
        '121',
        '323',
        '626',
        '818',
        '929',
        'Atenza',
        'AZ-1',
        'AZ-Offroad',
        'AZ-Wagon',
        'B-series',
        'Carol',
        'Cronos',
        'Demio',
        'Eunos 500',
        'Eunos 800',
        'Lantis',
        'Laputa',
        'Proceed Levante',
        '2',
        'Millenia',
        'MPV',
        'MX-3',
        'MX-5',
        'MX-6',
        'Navajo',
        'Premacy',
        'Revue',
        'RX-7',
        'RX-8',
        'Scrum',
        'Sentia',
        'Spiano',
        'Tribute',
        'Xedos 6',
        'Xedos 9',
        '3',
        'CX-7',
        '1000',
        '1300',
        '6',
        '5',
        'CX-9',
        'Protege',
        'Capella',
        'Familia',
        'BT-50',
        'Luce',
        'Bongo',
        'Bongo Friendee',
        'Verisa',
        'Axela',
        'Roadster',
        '616',
        'Biante',
        'Proceed Marvie',
        'Efini MS-8',
        'Eunos 300',
        'Efini MS-9',
        'Persona',
        'CX-5',
        'Efini MS-6',
        'Eunos Cosmo',
        '3 MPS',
        '6 MPS',
        'Eunos 100',
        'CX-3',
        'Cosmo',
    ],
    McLaren: [
        'F1',
        'MP4-12C',
        'P1',
        '650S',
        '675LT',
        '570S',
        '540C',
        '570GT',
        '720S',
    ],
    Mega: ['Club', 'Track', 'Monte Carlo'],
    'Mercedes-Benz': [
        '190 (W201)',
        'A-klasse',
        'C-klasse',
        'CL-klasse',
        'CLK-klasse',
        'E-klasse',
        'G-klasse',
        'M-klasse',
        'S-klasse',
        'SLK-klasse',
        'Vaneo',
        'CLS-klasse',
        'SLR McLaren',
        'B-klasse',
        'R-klasse',
        'GL-klasse',
        'Viano',
        'Vito',
        'CLC-klasse',
        'GLK-klasse',
        'SLS AMG',
        'SL-klasse',
        'W123',
        'W124',
        'W114',
        'W115',
        'V-klasse',
        'CLA-klasse',
        'GLA-klasse',
        'Citan',
        'AMG GT',
        'Maybach S-klasse',
        'A-klasse AMG',
        'C-klasse AMG',
        'CL-klasse AMG',
        'CLA-klasse AMG',
        'CLK-klasse AMG',
        'CLS-klasse AMG',
        'G-klasse AMG',
        'G-klasse AMG 6x6',
        'GLA-klasse AMG',
        'M-klasse AMG',
        'SLK-klasse AMG',
        'R-klasse AMG',
        'SL-klasse AMG',
        'S-klasse AMG',
        'E-klasse AMG',
        'GL-klasse AMG',
        'GLE',
        'AMG GLE',
        'GLE Coupe',
        'AMG GLE Coupe',
        'GLC',
        'W136',
        '190 SL',
        'W110',
        'W189',
        'W100',
        'W121',
        'W120',
        'GLS-klasse',
        'GLS-klasse AMG',
        'W108',
        'SLC-klasse',
        'SLC-klasse AMG',
        'W186',
        'W111',
        'W128',
        'AMG GLC',
        'GLC Coupe',
        'W188',
        'AMG GLC Coupe',
        'X-klasse Concept',
    ],
    Mercury: [
        'Marauder',
        'Mountaineer',
        'Mystique',
        'Sable',
        'Topaz',
        'Tracer',
        'Villager',
        'Capri',
        'Cougar',
        'Grand Marquis',
        'Montego',
        'Monterey',
        'Milan',
        'Mariner',
        'Marquis',
        'Eight',
    ],
    MG: [
        'F',
        'Midget',
        'TF',
        'Xpower SV',
        'ZR',
        'ZS',
        'ZT',
        'MGB',
        'Maestro',
        'Metro',
        'RV8',
        'Montego',
        '550',
        '6',
        '350',
        '5',
        '3',
        'GS',
        '750',
    ],
    Minelli: ['TF 1800'],
    MINI: [
        'Hatch',
        'Clubman',
        'Countryman',
        'Paceman',
        'Cabrio',
        'Coupe',
        'Roadster',
    ],
    Mitsubishi: [
        '3000 GT',
        'Airtrek',
        'Legnum',
        'Carisma',
        'Celeste',
        'Challenger',
        'Chariot',
        'Colt',
        'Cordia',
        'Debonair',
        'Diamante',
        'Dingo',
        'Dion',
        'Eclipse',
        'eK',
        'Emeraude',
        'FTO',
        'Galant',
        'Grandis',
        'GTO',
        'Libero',
        'Minica',
        'Mirage',
        'Outlander',
        'Pajero',
        'Pajero Junior',
        'Pajero iO',
        'Pajero Pinin',
        'Pistachio',
        'Proudia',
        'RVR',
        'Sapporo',
        'Sigma',
        'Space Gear',
        'Space Runner',
        'Space Star',
        'Space Wagon',
        'Starion',
        'Toppo',
        'Town Box',
        'Tredia',
        'Delica',
        'Lancer',
        'Aspire',
        'Endeavor',
        'L200',
        'Raider',
        'Montero',
        'Montero Sport',
        'i',
        'Jeep J',
        'Minicab',
        'ASX',
        'Eterna',
        'i-MiEV',
        'Lancer Evolution',
        'Pajero Sport',
        'Lancer Cargo',
        'Pajero Mini',
        'Attrage',
        'Dignity',
        'Strada',
        'Lancer Ralliart',
        'Delica D:2',
        'Delica D:3',
    ],
    Morgan: [
        'Aero 8',
        '4/4',
        'Plus 8',
        'Plus 4',
        'Roadster',
        'AeroMax',
        'Aero SuperSports',
        'Aero Coupe',
        '3 Wheeler',
        '4 Seater',
    ],
    Moskvich: [
        '2140',
        'Yuriy Dolgorukiy',
        '2141',
        'Svyatogor',
        '403',
        '407',
        '423',
        '427',
        '2136',
        '2138',
        'Knyaz Vladimir',
        '408',
        '401',
        '402',
        '400',
        '412',
        '2137',
        '410',
        'Ivan Kalita',
        'Duet',
        '411',
        '426',
        '424',
    ],
    Nissan: [
        '100NX',
        '200SX',
        '280ZX',
        '300ZX',
        '350Z',
        'Almera',
        'Almera Tino',
        'Altima',
        'Avenir',
        'Bassara',
        'Bluebird',
        'Cedric',
        'Cefiro',
        'Cherry',
        'Cima',
        'Crew',
        'Cube',
        'Elgrand',
        'Gloria',
        'Largo',
        'Laurel',
        'Leopard',
        'Liberty',
        'Lucino',
        'Micra',
        'Moco',
        'Murano',
        'Pathfinder',
        'Prairie',
        'Presage',
        'Presea',
        'President',
        'Primera',
        'Pulsar',
        'Quest',
        "R''nessa",
        'Rasheen',
        'Safari',
        'Sentra',
        'Serena',
        'Silvia',
        'Skyline',
        'Skyline Crossover',
        'Stagea',
        'Stanza',
        'Sunny',
        'Terrano',
        'Terrano Regulus',
        'Tino',
        'Wingroad',
        'X-Terra',
        'X-Trail',
        'Maxima',
        'Patrol',
        'Vanette',
        'Datsun',
        'Teana',
        'Note',
        'Navara (Frontier)',
        'Urvan',
        'Titan',
        'Armada',
        'Primastar',
        'Qashqai',
        'Lafesta',
        'Rogue',
        'March',
        'AD',
        'Fairlady Z',
        'Expert',
        'Versa',
        'Tiida',
        'Mistral',
        'GT-R',
        'Fuga',
        'NP 300',
        '180SX',
        '370Z',
        'Leaf',
        'Caravan',
        'Langley',
        'Figaro',
        '240SX',
        'Clipper',
        'NX Coupe',
        'Juke',
        'Otti (Dayz)',
        'BE-1',
        'Bluebird Sylphy',
        'NV200',
        'Dualis',
        'Pao',
        'Pino',
        'Pixo',
        'Almera Classic',
        'Roox',
        'NV350 Caravan',
        'Qashqai+2',
        'Kix',
        'Liberta Villa',
        'Juke Nismo',
        'Latio',
    ],
    Oldsmobile: [
        'Achieva',
        'Aurora',
        'Bravada',
        'Eighty-Eight',
        'Intrigue',
        'Silhouette',
        'Cutlass',
        'Alero',
        'Ninety-Eight',
        'Omega',
        'Cutlass Supreme',
        'Cutlass Ciera',
        'Cutlass Calais',
        'Toronado',
    ],
    Opel: [
        'Admiral',
        'Agila',
        'Ascona',
        'Calibra',
        'Diplomat',
        'Manta',
        'Meriva',
        'Monterey',
        'Rekord',
        'Signum',
        'Sintra',
        'Speedster',
        'Tigra',
        'Kadett',
        'Omega',
        'Astra',
        'Zafira',
        'Commodore',
        'Frontera',
        'Vectra',
        'Corsa',
        'Senator',
        'Combo',
        'Campo',
        'Antara',
        'Vita',
        'Insignia',
        'Mokka',
        'Ampera',
        'Monza',
        'GT',
        'Cascada',
        'Adam',
        'Vivaro',
        'Astra OPC',
        'Corsa OPC',
        'Insignia OPC',
        'Meriva OPC',
        'Vectra OPC',
        'Zafira OPC',
        'Olympia',
        'Karl',
        'Kapitan',
        'P4',
        'Crossland X',
    ],
    Osca: ['2500 GT'],
    Pagani: ['Zonda', 'Huayra'],
    Panoz: ['Roadster', 'Esperante'],
    Perodua: [
        'Kelisa',
        'Kenari',
        'Kancil',
        'Viva',
        'Kembara',
        'Nautica',
        'Alza',
        'MyVi',
    ],
    Peugeot: [
        '106',
        '205',
        '206',
        '305',
        '306',
        '307',
        '309',
        '405',
        '406',
        '505',
        '605',
        '607',
        '806',
        '807',
        '1007',
        '107',
        'Partner',
        '207',
        '407',
        'Expert',
        'Bipper',
        '4007',
        '308',
        '3008',
        '5008',
        'RCZ',
        '508',
        '4008',
        '408',
        '104',
        '204',
        '304',
        '504',
        '604',
        '208',
        '301',
        '2008',
        '108',
        '205 GTi',
        '208 GTi',
        'iOn',
        '308 GTi',
        '402',
        '203',
        'Traveller',
        '201',
        '202',
        '403',
        '404',
    ],
    Plymouth: [
        'Acclaim',
        'Breeze',
        'Laser',
        'Sundance',
        'Neon',
        'Prowler',
        'Voyager',
        'Caravelle',
        'Turismo',
        'Barracuda',
        'Road Runner',
        'Fury',
        'Valiant',
    ],
    Pontiac: [
        '6000',
        'Aztek',
        'Bonneville',
        'Firebird',
        'Grand AM',
        'Grand Prix',
        'Montana',
        'Phoenix',
        'Sunbird',
        'Vibe',
        'Sunfire',
        'GTO',
        'Trans Sport',
        'G6',
        'Solstice',
        'Torrent',
        'LeMans',
        'Tempest',
        'Fiero',
        'Parisienne',
        'G4',
        'G5',
        'G8',
        'Catalina',
    ],
    Porsche: [
        '911',
        '928',
        '959',
        'Boxster',
        'Carrera GT',
        'Cayenne',
        'Cayman',
        'Panamera',
        '924',
        '944',
        '968',
        '914',
        '918 Spyder',
        'Macan',
        '911 GT2',
        '911 GT3',
        'Cayman GT4',
        '356',
        '718 Boxster',
        '718 Cayman',
        '911 R',
    ],
    Premier: ['118NE', 'Padmini'],
    Proton: [
        'Perdana',
        'Satria',
        'Wira (400 Series)',
        'Saga',
        'Waja',
        'Juara',
        'Persona',
        'Gen-2',
        'Exora',
        'Inspira',
        'Preve',
    ],
    PUCH: ['Pinzgauer', 'G-modell'],
    Puma: ['GTE', 'GTB'],
    Reliant: ['Scimitar Sabre'],
    Renault: [
        '19',
        'Avantime',
        'Clio',
        'Espace',
        'Kangoo',
        'Laguna',
        'Megane',
        'Safrane',
        'Scenic',
        'Sport Spider',
        'Symbol',
        'Twingo',
        'Vel Satis',
        'Modus',
        'Logan',
        'Rodeo',
        'Trafic',
        'Koleos',
        'Fluence',
        'Sandero',
        'Latitude',
        'Twizy',
        'Duster',
        '11',
        '9',
        '12',
        '14',
        '15',
        '16',
        '17',
        '18',
        '20',
        '21',
        '25',
        '30',
        '4',
        '5',
        '6',
        'Fuego',
        'Wind',
        'ZOE',
        'Captur',
        'Lodgy',
        'Dokker',
        'Clio V6',
        'Clio RS',
        'Megane RS',
        '8',
        'Kadjar',
        'Talisman',
        'Sandero RS',
        'KWID',
        '10',
        '4CV',
        'Caravelle',
        'Dauphine',
        'Floride',
        'Fregate',
        'Vivastella',
        'Kaptur',
        'Alaskan',
    ],
    'Rolls-Royce': [
        'Corniche',
        'Park Ward',
        'Silver Seraph',
        'Silver Spur',
        'Ghost',
        'Phantom',
        'Wraith',
        'Silver Cloud',
        'Silver Shadow',
        'Silver Wraith',
        'Dawn',
        'Camargue',
        'Silver Ghost',
        '20/25',
    ],
    Ronart: ['Lightning'],
    Rover: [
        'SD1',
        'P6',
        '45',
        '600',
        'Mini',
        '75',
        '100',
        '200',
        '25',
        '400',
        '800',
        'Metro',
        'Streetwise',
        'P4',
        'P3',
    ],
    Saab: [
        '9-3',
        '9-5',
        '900',
        '96',
        '9-7X',
        '90',
        '9-2X',
        '9-4X',
        '9000',
        '95',
        '99',
        '93',
        'Sonett',
    ],
    Saleen: ['S7'],
    'Renault Samsung': ['SM3', 'SM5', 'SM7'],
    Saturn: [
        'ION',
        'LW',
        'SW',
        'VUE',
        'LS',
        'SC',
        'SL',
        'Aura',
        'Sky',
        'Relay',
        'Outlook',
        'Astra',
    ],
    SEAT: [
        'Ibiza',
        '133',
        'Alhambra',
        'Arosa',
        'Cordoba',
        'Fura',
        'Leon',
        'Malaga',
        'Marbella',
        'Ronda',
        'Toledo',
        'Altea',
        'Exeo',
        'Ibiza Cupra',
        'Leon Cupra',
        'Mii',
        'Ateca',
    ],
    Skoda: [
        'Fabia',
        'Felicia',
        'Octavia',
        'Rapid',
        'Superb',
        'Roomster',
        'Yeti',
        '100 Series',
        'Favorit',
        'Citigo',
        'Fabia RS',
        'Octavia RS',
        'Popular',
        'Kodiaq',
    ],
    Spectre: ['R42'],
    SsangYong: [
        'Chairman',
        'Kallista',
        'Rexton',
        'Korando',
        'Musso',
        'Rodius',
        'Kyron',
        'Actyon',
        'Actyon Sports',
        'Korando Family',
        'Stavic',
        'Korando Sports',
        'Tivoli',
        'Nomad',
        'XLV',
    ],
    Subaru: [
        'Baja',
        'Domingo',
        'Forester',
        'Impreza',
        'Justy',
        'Legacy',
        'Leone',
        'Pleo',
        'SVX',
        'Traviq',
        'Vivio',
        'XT',
        'Tribeca',
        'R1',
        'R2',
        'Outback',
        'Stella',
        'Exiga',
        'Alcyone',
        'Dex',
        'Sambar',
        'Lucra',
        'Trezia',
        'XV',
        'Libero',
        'BRZ',
        'WRX',
        'Impreza WRX',
        'WRX STi',
        'Impreza WRX STi',
        'Levorg',
        '360',
    ],
    Suzuki: [
        'Aerio',
        'Cappuccino',
        'Grand Vitara',
        'Ignis',
        'Jimny',
        'Liana',
        'MR Wagon',
        'Swift',
        'X-90',
        'Alto',
        'Wagon R+',
        'Escudo',
        'Splash',
        'Every',
        'Reno',
        'Wagon R',
        'Verona',
        'Kizashi',
        'Cervo',
        'Landy',
        'Baleno',
        'Forenza',
        'Kei',
        'SX4',
        'XL7',
        'Spacia',
        'Ertiga',
        'Solio',
        'Palette',
        'Celerio',
        'Vitara',
        'Samurai',
        'Twin',
        'Equator',
    ],
    Talbot: ['Horizon', 'Samba', 'Solara', 'Tagora', 'Avenger', '1510'],
    TATA: [
        'Aria',
        'Estate',
        'Indica',
        'Sumo',
        'Safari',
        'Sierra',
        'Indigo',
        'Nano',
        'Xenon',
    ],
    Tatra: ['T613', 'T700', '57', 'T603', '77', '87', '80'],
    Tofas: ['Kartal', 'Sahin', 'Serce', 'Murat 131', 'Murat 124'],
    Toyota: [
        '4Runner',
        'Allion',
        'Altezza',
        'Aristo',
        'Avalon',
        'Avensis',
        'Avensis Verso',
        'bB',
        'Blizzard',
        'Brevis',
        'Caldina',
        'Cami',
        'Camry',
        'Carina',
        'Celica',
        'Chaser',
        'Corolla',
        'Corolla Verso',
        'Corona',
        'Cressida',
        'Cresta',
        'Crown',
        'Curren',
        'Cynos',
        'Duet',
        'Gaia',
        'Harrier',
        'Highlander',
        'Ipsum',
        'Kluger',
        'Land Cruiser',
        'Mark II',
        'Mega Cruiser',
        'MR2',
        'Nadia',
        'Opa',
        'Origin',
        'Paseo',
        'Picnic',
        'Platz',
        'Premio',
        'Previa',
        'Prius',
        'Progres',
        'Pronard',
        'Raum',
        'RAV 4',
        'Scepter',
        'Sequoia',
        'Sera',
        'Sienna',
        'Soarer',
        'Starlet',
        'Supra',
        'Tercel',
        'Verossa',
        'Vista',
        'Vitz',
        'Windom',
        'Yaris',
        'Yaris Verso',
        'HiAce',
        'LiteAce',
        'WiLL',
        'Aygo',
        'Century',
        'Hilux',
        'Echo',
        'Estima',
        'Fortuner',
        'FunCargo',
        'Granvia',
        'Ist',
        'MasterAce Surf',
        'Matrix',
        'Noah',
        'Probox',
        'Regius',
        'RegiusAce',
        'Sparky',
        'Sprinter',
        'Succeed',
        'TownAce',
        'Tacoma',
        'Voltz',
        'Voxy',
        'Wish',
        'Auris',
        'Tundra',
        'Alphard',
        'Corsa',
        'Sienta',
        'FJ Cruiser',
        'Cavalier',
        'Allex',
        'Mark X',
        'Mark X ZiO',
        'Passo',
        'Aurion',
        'Porte',
        'ISis',
        'Venza',
        'Ractis',
        'Corolla Rumion',
        'Urban Cruiser',
        'iQ',
        'Belta',
        'Blade',
        'Rush',
        'Celsior',
        'Innova',
        'Vellfire',
        'Soluna',
        'Verso',
        'Vios',
        'Vanguard',
        'Carina ED',
        'Crown Majesta',
        'Land Cruiser Prado',
        'GT86',
        'Passo Sette',
        'Hilux Surf',
        'WiLL Cypha',
        'Sai',
        'Verso-S',
        'Prius v (+)',
        'Prius c',
        'Sprinter Carib',
        'Sprinter Trueno',
        'Sprinter Marino',
        'ProAce',
        'Camry Solara',
        'Camry (Japan)',
        'Corolla Spacio',
        'Publica',
        'Mirai',
        '2000GT',
        'Pixis Epoch',
        'Pixis Mega',
        'Pixis Space',
        'Aqua',
        'C-HR',
    ],
    Trabant: ['1.1', 'P 601'],
    Triumph: ['TR7', 'TR8', 'TR6', 'Stag', 'Spitfire'],
    TVR: [
        '390',
        '450',
        'Cerbera',
        'Chimaera',
        'Griffith',
        'S-Series',
        'Tamora',
        '280',
        '350',
        '420',
        '400',
        'Sagaris',
        'Tuscan',
    ],
    UAZ: [
        '3159',
        '3153',
        '3160',
        '3162 Simbir',
        '469',
        'Patriot',
        'Pickup',
        'Hunter',
        '3151',
    ],
    Vauxhall: [
        'Carlton',
        'Ventora',
        'Viceroy',
        'Victor',
        'Viva',
        'Astra',
        'Royale',
        'Vectra',
        'VXR8',
        'Adam',
    ],
    'VAZ (Lada)': [
        '2101',
        '2102',
        '2103',
        '2104',
        '2105',
        '2106',
        '2107',
        '2108',
        '2109',
        '2110',
        '2111',
        '2112',
        '2113',
        '2114',
        '2115',
        '2120 Nadezhda',
        '2123',
        '2131 (4x4)',
        '2328',
        'Kalina',
        '1111 Oka',
        '2129',
        'Priora',
        '2329',
        'Revolution',
        'Granta',
        'Largus',
        '2121 (4x4)',
        '21099',
        'Vesta',
        'XRAY',
        'EL Lada',
    ],
    Vector: ['M12', 'W8 Twin Turbo'],
    Venturi: ['210', '260 LM', '300 Atlantique', '400 GT'],
    Volkswagen: [
        '181',
        'Type 4',
        'Corrado',
        'Derby',
        'Golf',
        'Golf Plus',
        'Iltis',
        'Type 1',
        'Lupo',
        'Beetle',
        'Passat',
        'Phaeton',
        'Polo',
        'Santana',
        'Scirocco',
        'Sharan',
        'Taro',
        'Touareg',
        'Touran',
        'Vento',
        'Fox',
        'Jetta',
        'Bora',
        'Pointer',
        'Eos',
        'Caddy',
        'Tiguan',
        'Multivan',
        'Amarok',
        'Routan',
        'Golf Country',
        'up!',
        'XL1',
        'Passat CC',
        'Golf Sportsvan',
        'Passat (North America)',
        'Caravelle',
        'Transporter',
        'California',
        'Golf GTI',
        'Scirocco R',
        'Golf R',
        'Lupo GTI',
        'Polo R WRC',
        'Polo GTI',
        'Karmann-Ghia',
        'Type 2',
        'Golf R32',
        'K70',
        'Arteon',
    ],
    Volvo: [
        '300 Series',
        '440',
        '460',
        '480',
        '740',
        '760',
        '780',
        '850',
        '940',
        'S40',
        'S60',
        'S70',
        'S80',
        'S90',
        'V40',
        'V90',
        'XC90',
        'V70',
        'C70',
        'XC70',
        'V50',
        'C30',
        'XC60',
        'Laplander',
        'V60',
        '140 Series',
        '164',
        '240 Series',
        '260 Series',
        '66',
        '960',
        'V40 Cross Country',
        'V60 Cross Country',
        'S60 Cross Country',
        '120 Series',
        'P1800',
        'P1900',
        'V90 Cross Country',
    ],
    Wartburg: ['353', '1.3'],
    Zastava: ['Skala', 'Yugo', '10', 'Florida'],
    ZAZ: [
        '1102 «Tavriya»',
        '1103 «Slavuta»',
        '965',
        '966',
        '968',
        'Sens',
        '1105 «Dana»',
        'Chance',
        'Forza',
        'Vida',
        'Lanos',
    ],
    Koenigsegg: ['CC8S', 'CCX', 'Agera', 'CCR', 'One:1', 'Regera'],
    'Xin Kai': ['SR-V X3', 'SUV X3', 'Pickup X3'],
    Scion: ['xA', 'xB', 'tC', 'xD', 'iQ', 'FR-S', 'iM', 'iA'],
    Beijing: ['BJ2020', 'BJ212'],
    Invicta: ['S1'],
    Derways: [
        'Cowboy',
        'Shuttle',
        'Aurora',
        'Plutus',
        'Antelope',
        'Land Crown',
        'Saladin',
    ],
    'Iran Khodro': ['Samand', 'Paykan', 'Soren'],
    'Great Wall': [
        'Safe',
        'Sing RUV',
        'Sailor',
        'Wingle',
        'Pegasus',
        'Socool',
        'Peri',
        'Coolbear',
        'Florid',
        'Cowry (V80)',
        'Voleex C10 (Phenom)',
        'Deer',
        'Hover',
        'Hover M2',
        'Hover M4',
        'Hover M1 (Peri 4x4)',
        'Hover H6',
        'Hover H5',
        'Hover H3',
        'Voleex C30',
    ],
    Wiesmann: ['Roadster', 'GT'],
    Hafei: ['Brio', 'Saibao', 'Sigma', 'Simbo', 'Princip'],
    Mitsuoka: [
        'Galue',
        'Le-Seyde',
        'Ryoga',
        'Nouera',
        'Himiko',
        'Orochi',
        'Ray',
        'Viewt',
        'Yuga',
        'Zero 1',
        'Like',
        'Galue 204',
    ],
    Dadi: ['City Leading', 'Shuttle', 'Smoothing'],
    Datsun: [
        '280ZX',
        '720',
        'Cherry',
        'Sunny',
        'Violet',
        'Stanza',
        'Bluebird',
        'GO',
        'GO+',
        'on-DO',
        'Urvan',
        'mi-DO',
    ],
    Geo: ['Metro', 'Prizm', 'Storm', 'Spectrum', 'Tracker'],
    Metrocab: ['Metrocab I', 'Metrocab II (TTT)'],
    Smart: ['Roadster', 'Fortwo', 'Forfour'],
    Spyker: ['C8', 'C12'],
    BYD: [
        'Flyer',
        'F3',
        'F0',
        'F6',
        'F8',
        'E6',
        'G3',
        'G6',
        'L3',
        'M6',
        'S6',
        'F5',
    ],
    Chery: [
        'Tiggo (T11)',
        'Oriental Son (B11)',
        'Amulet (A15)',
        'Fora (A21)',
        'Sweet (QQ)',
        'QQ6 (S21)',
        'Kimo (A1)',
        'CrossEastar (B14)',
        'M11 (A3)',
        'Bonus (A13)',
        'IndiS (S18D)',
        'Very (A13)',
        'Tiggo 5',
        'Bonus 3 (E3/A19)',
        'Arrizo 7',
        'Tiggo 3',
        'Tiggo 2',
    ],
    Donkervoort: ['D8', 'D8 GTO'],
    Geely: [
        'Beauty Leopard',
        'Haoqing',
        'MR',
        'CK (Otaka)',
        'MK',
        'FC (Vision)',
        'MK Cross',
        'Emgrand EC7',
        'SC7',
        'LC (Panda)',
        'LC (Panda) Cross',
        'Emgrand EC8',
        'Emgrand X7',
        'GC6',
        'GC9',
        'Emgrand 7',
        'Emgrand GT',
    ],
    Landwind: ['X6', 'X5', 'Forward', 'Fashion (CV9)', 'X9', 'X7'],
    Noble: ['M12 GTO', 'M600'],
    Qvale: ['Mangusta'],
    Tianma: ['Century'],
    Tianye: ['Admiral'],
    ZIL: ['114', '117', '4104', '111'],
    LUAZ: ['967', '1302 Volyny', '969'],
    Lifan: [
        'Breez (520)',
        'Solano',
        'Smily',
        'X60',
        'Cebrium (720)',
        'Celliya (530)',
        'X50',
        'Myway',
    ],
    ChangFeng: ['SUV (CS6)', 'Flying'],
    ShuangHuan: ['Sceo', 'Noble'],
    Brilliance: [
        'M1 (BS6)',
        'M2 (BS4)',
        'M3 (BC3)',
        'FRV (BS2)',
        'V5',
        'H530',
        'H230',
    ],
    Soueast: ['Lioncel'],
    ZX: ['Landmark', 'Grand Tiger', 'Admiral'],
    JAC: [
        'M1 (Refine)',
        'S1 (Rein)',
        'J3 (Tongyue,Tojoy)',
        'J7 (Binyue)',
        'J5 (Heyue)',
        'J6 (Heyue RS)',
        'J2 (Yueyue)',
        'S5 (Eagle)',
        'S3',
        'J4 (Heyue A30)',
        'M5',
    ],
    Fuqi: ['6500 (Land King)'],
    HuangHai: ['Antelope', 'Plutus', 'Landscape'],
    SMZ: ['S-3A', 'S-3D'],
    Gonow: ['Troy'],
    'Baltijas Dzips': ['BD-1322'],
    DongFeng: ['MPV', 'Oting', 'Rich', 'H30 Cross', 'S30', 'AX7', 'A9', '370'],
    IVECO: ['Massif'],
    TagAZ: ['Tager', 'Road Partner', 'Vega', 'C-30', 'Aquila', 'C10', 'C190'],
    Bufori: ['La Joya', 'Geneva'],
    Changan: [
        'CM-8',
        'Z-Shine',
        'CS35',
        'Benni',
        'Eado',
        'Raeton',
        'CS75',
        'Alsvin V7',
    ],
    KTM: ['X-Bow'],
    JMC: ['Baodian'],
    Tesla: ['Roadster', 'Model S', 'Model X'],
    Marussia: ['B1', 'B2'],
    Vortex: ['Corda', 'Tingo', 'Estina'],
    Haima: ['3', '7', 'M3', 'S5'],
    Tazzari: ['Zero'],
    Foton: ['Midi', 'Tunland', 'Sauvana'],
    Ariel: ['Atom'],
    Santana: ['PS-10'],
    Zotye: ['Nomad (RX6400)', 'Z300', 'T600', 'Z100', 'SR9'],
    Luxgen: ['Luxgen5', 'Luxgen7 SUV', 'Luxgen7 MPV', 'U7 Turbo', 'U6 Turbo'],
    'AM General': ['HMMWV (Humvee)'],
    Fisker: ['Karma'],
    Ecomotors: ['Estrima Biro'],
    'E-Car': ['GD04B'],
    Byvin: ['BD326J (Moca)', 'BD132J (CoCo)'],
    Maybach: ['57', '62'],
    Piaggio: ['Porter'],
    Alpina: [
        'XD3',
        'Roadster',
        'B4',
        'C1',
        'B6',
        'C2',
        'B3',
        'B8',
        'D3',
        'B7',
        'B9',
        'B10',
        'D10',
        'B5',
        'D5',
        'B11',
        'B12',
    ],
    'Eagle Cars': ['SS'],
    Kanonir: ['2317'],
    Westfield: ['SEi & Sport', 'SEiGHT'],
    Microcar: ['M.Go', 'M8', 'Virgo', 'MC', 'F8C'],
    Morris: ['Marina', 'Eight'],
    'Liebao Motor': ['Leopard'],
    Jensen: ['S-V8', 'Interceptor'],
    'Yo-mobile': ['E-Krossover'],
    Bronto: ['Ris', 'Fora'],
    Tramontana: ['Tramontana'],
    Marlin: ['Sportster', '5EXi'],
    Avtokam: ['2160', '2163', '3101'],
    Qoros: ['3'],
    Brabus: ['7.3S', 'SV12', 'M V12', 'ML 63 Biturbo'],
    Renaissance: ['Tropica Roadster'],
    Hawtai: ['Boliger'],
    Ultima: ['GTR'],
    Gordon: ['Roadster'],
    Haval: ['H6', 'H8', 'H9', 'H2'],
    DS: ['5', '3', '4'],
    PGO: ['Hemera', 'Cevennes', 'Speedster II'],
    'Shanghai Maple': ['C81', 'C51', 'C52', 'C31'],
    Zenvo: ['ST1'],
    'W Motors': ['Lykan Hypersport', 'Fenyr Supersport'],
    Rezvani: ['Beast'],
    Rimac: ['Concept_One'],
    Adler: ['Trumpf Junior'],
    Willys: ['MB'],
    DeSoto: ['Firedome', 'Fireflite'],
    Packard: ['Clipper', 'One-Twenty', 'Twelve', '200/250'],
    Kombat: ['T98'],
    Borgward: ['2000'],
    Ravon: ['Gentra', 'Matiz', 'Nexia R3', 'R2', 'R4'],
    ZiS: ['110', '101'],
    AMC: ['Hornet'],
    Zenos: ['E10'],
    Hudson: ['Deluxe Eight'],
    Batmobile: ['1989'],
    Excalibur: ['Series IV', 'Series V'],
    Genesis: ['G90', 'G80'],
    Wanderer: ['W50'],
    Zibar: ['MK2'],
    Delage: ['D6'],
    Steyr: ['1500'],
    Hanomag: ['Rekord'],
    Bilenkin: ['Vintage'],
    Think: ['City'],
    Bajaj: ['Qute'],
};